image: bipeen/new_drone
name: hello
script:  
  - mvn clean install
  - wrapdocker &  
  - sleep 5
  - whoami
  - sudo start docker
  - sudo docker build -H unix:///var/run/docker.sock -t bipeen/docker_drone . 

